language: node_js
install:
  - "npm install npm -g"
  - "npm install mocha@1.16.0"
  - "npm install $(node -e \"console.log(Object.keys(require('./package').devDependencies).filter(function(k) { return k !== 'mocha'; }).join(' '))\")"
node_js:
  - "0.8"
  - "0.10"
